name: Continuous Deployment (CD)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Build and Push Docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/advshop:latest

      - name: Deploy to Koyeb
        run: |
          curl -L https://bin.koyeb.com/install.sh | bash
          koyeb login --token ${{ secrets.KOYEB_TOKEN }}
          koyeb app init advshop --docker "${{ secrets.DOCKER_USERNAME }}/advshop:latest" \
          --ports 8080:http --routes "/:8080" --regions fra
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}