name: Continuous Deployment (CD)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/advshop:latest
      - name: Install Koyeb CLI
          run: |
            curl -L https://github.com/koyeb/koyeb-cli/releases/latest/download/koyeb_Linux_x86_64.tar.gz | tar -xz
            sudo mv koyeb /usr/local/bin/
      - name: Deploy to Koyeb
          env:
            KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
          run: |
            koyeb login --token $KOYEB_TOKEN
            koyeb app init advshop --docker "${{ secrets.DOCKER_USERNAME }}/advshop:latest" \
              --ports 8080:http \
              --routes "/:8080" \
              --regions fra  # Replace 'fra' with your preferred region (e.g., 'sgp', 'iad')