name: Continuous Deployment (CD)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rachelmathilda14/advshop:latest

      - name: Deploy to Koyeb
        run: |
          koyeb login --token ${{ secrets.KOYEB_TOKEN }}
          koyeb app init eshop \
            --docker advshop:latest \
            --ports 8080:http \
            --routes /:8080 \
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}