name: Continuous Deployment (CD)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Build and Push Docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/advshop:latest

      - name: Deploy to Koyeb
        run: |
          curl -L https://bin.koyeb.com/install.sh | bash
          koyeb login --token ${{ secrets.KOYEB_TOKEN }}
          koyeb app init example-java \
            --git github.com/<YOUR_GITHUB_USERNAME>/<YOUR_REPOSITORY_NAME> \
            --git-branch main \
            --git-run-command "java -jar target/example-java-1.0-SNAPSHOT.jar"
            --ports 3000:http \
            --routes /:3000 \
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}